Update marker structure
I've updated the events matrix to [timesample 0 marker] instead of [timesample marker 0], to match what mne expects. This fixed an error given by mne after reading the converted files and extracting epochs with mne.Epochs() :

\epochs.py in __init__(***failed resolving arguments***)
    252                            '(event id %i)' % (key, val))
    253                     if on_missing == 'error':
--> 254                         raise ValueError(msg)
    255                     elif on_missing == 'warning':
    256                         warn(msg)

ValueError: No matching events found for xxx (event id xxx)